# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
  paths:
    - .cache/pip
    - venv/
    - venv_pypy/

.default:
  image: python:3.9
  before_script:
    - uname -a
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - pip install tox

health:
  extends: .default
  script:
    - tox -e flake8
    - tox -e spell
    - tox -e twine

mypy:
  extends: .default
  script:
    - tox -e mypy

py39:
  extends: .default
  image: python:3.9
  script:
    - apt update
    - apt install -qy sudo
    - apt install -qy tcpdump
    - DEBIAN_FRONTEND=noninteractive apt install -qy --force-yes wireshark-common
    - ./.config/ci/install.sh ''
    - ./.config/ci/test.sh 3.9 non_root

py27:
  extends: .default
  image: python:2.7
  script:
    - apt update
    - apt install -qy sudo
    - apt install -qy tcpdump
    - DEBIAN_FRONTEND=noninteractive apt install -qy --force-yes wireshark-common
    - ./.config/ci/install.sh ''
    - ./.config/ci/test.sh 2.7 non_root

pypy2:
  image: pypy:2
  script:
    - pip install virtualenv
    - virtualenv venv_pypy
    - source venv_pypy/bin/activate
    - pip install tox
    - apt update
    - apt install -qy sudo
    - apt install -qy tcpdump
    - DEBIAN_FRONTEND=noninteractive apt install -qy --force-yes wireshark-common
    - ./.config/ci/install.sh ''
    - ./.config/ci/test.sh pypy2 non_root

pypy3:
  image: pypy:3
  script:
    - pip install virtualenv
    - virtualenv venv_pypy
    - source venv_pypy/bin/activate
    - pip install tox
    - apt update
    - apt install -qy sudo
    - apt install -qy tcpdump
    - DEBIAN_FRONTEND=noninteractive apt install -qy --force-yes wireshark-common
    - ./.config/ci/install.sh ''
    - ./.config/ci/test.sh pypy3 non_root
